[phases.setup]
# Tell Nixpacks which PHP + extensions we want
nixPkgs = [
    "php83",
  "php83Extensions.gd",
  "php83Extensions.zip",
  "php83Extensions.pdo_mysql",
  "php83Extensions.redis",
  "php83Extensions.mbstring",
  "php83Extensions.bcmath",
  "php83Extensions.tokenizer",
  "php83Extensions.xml",
  "php83Extensions.ctype",
  "php83Extensions.fileinfo",
  "php83Extensions.openssl"
]

[variables]
# Force composer to use production-ready settings
COMPOSER_INSTALL_FLAGS="--ignore-platform-req=ext-zip --ignore-platform-req=ext-gd"

[start]
# Run Laravel on Railway’s assigned port
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[deploy]
# Run migrations automatically before serving
cmd = "php artisan migrate --force"
